version: "3"

services:
  postgres:
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shuploader
volumes:
  postgres:
